plugins {
    id 'com.android.application'
}

android {
    namespace 'cz.piskvorky.trener'
    compileSdk 34

    defaultConfig {
        applicationId "cz.piskvorky.trener"
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
